### ISSUE TITLE
compiled error

### ISSUE THREAD

**Issue by hjianhao** [crosbymichael/cgroups#6]
When I build my example, there are many errors as follow:

../vendor/github.com/crosbymichael/cgroups/hugetlb.go:45: cannot use limit.Limit (type uint64) as type int64 in argument to strconv.FormatInt
../vendor/github.com/crosbymichael/cgroups/memory.go:67: cannot use resources.Memory.Limit (type *uint64) as type *int64 in argument to g
../vendor/github.com/crosbymichael/cgroups/memory.go:67: cannot use resources.Memory.Swap (type *uint64) as type *int64 in argument to g
../vendor/github.com/crosbymichael/cgroups/memory.go:228: cannot use mem.Limit (type *uint64) as type *int64 in field value
../vendor/github.com/crosbymichael/cgroups/memory.go:232: cannot use mem.Swap (type *uint64) as type *int64 in field value
../vendor/github.com/crosbymichael/cgroups/memory.go:236: cannot use mem.Kernel (type *uint64) as type *int64 in field value
../vendor/github.com/crosbymichael/cgroups/memory.go:240: cannot use mem.KernelTCP (type *uint64) as type *int64 in field value

**Comment by homelessnessbo** [comment]
show example of code?

**Comment by hjianhao** [comment]
func PauseAndResumeByCgroup(ctx context.Context, id string) {
	control, err := cgroups.Load(cgroups.V1, cgroups.StaticPath("/docker/"+id))

	if err != nil {
		panic(err)
	}

	var pauseTotal, resumeTotal int64 = 0, 0

	for i := 0; i < 100; i++ {
		start := time.Now()
		if err := control.Freeze(); err != nil {
			panic(err)
		}
		end := time.Now()
		pauseTotal += (end.Sub(start).Nanoseconds()) / 1000000

		start = time.Now()
		if err := control.Thaw(); err != nil {
			panic(err)
		}
		end = time.Now()
		resumeTotal += (end.Sub(start).Nanoseconds()) / 1000000
	}

	fmt.Printf("container %s, Average pause time : %d ms, average resume time : %d ms. \n", id, pauseTotal/100, resumeTotal/100)
}

**Comment by hjianhao** [comment]
I found that in hugetlb.go, code is that strconv.FormatInt(limit.Limit, 10), but the limit.Limit's type is uint64, so need strconv.FormatUint(limit.Limit, 10)

int64 and uint64 mismatched also found in memory.go. 

I had modified the code, then compiled successful, you can check it.

**Comment by crosbymichael** [comment]
This can be from changes in the spec.  We just released a final RC so this package will need to be updated with the spec changes.

**Comment by crosbymichael** [comment]
Also, i'll add `vndr` to vendor the dependencies for this in a PR

**Comment by crosbymichael** [comment]
I updated master with the dependencies vendored and changes for the runtime-spec rc5.  It should build for you now.
